### PR TITLE
setup: tailwind css setup on components workspace

### PR DESCRIPTION
**Pull request by adamshcao**

### CODE REVIEW

**Comment by algreasley** [comment]
looks good .. a minor thing, but could you look at using just .js files as config (I know the .cjs is required in a world where ES modules are expected and we are using `module.exports = ..`

**Comment by adamshcao** [comment]
> looks good .. a minor thing, but could you look at using just .js files as config (I know the .cjs is required in a world where ES modules are expected and we are using `module.exports = ..`) but we should be able to use std ES-style .js or perhaps even .ts (like the vite config file)

image

I tried using .js for configs but keep running into this error? Not really sure where to go from here.

**Comment by algreasley** [comment]
> I tried using .js for configs but keep running into this error? Not really sure where to go from here.

I see .. only way to do this is to get the initiating (node-based) code to be ES too, I guess ... not to worry for now, I/we can look into this as a background task 👍🏻

**Comment by adamshcao** [comment]
> > I tried using .js for configs but keep running into this error? Not really sure where to go from here.
> 
> I see .. only way to do this is to get the initiating (node-based) code to be ES too, I guess ... not to worry for now, I/we can look into this as a background task 👍🏻

Managed to convert the tailwind config to .ts and the postcss to .js. Can't seem to get postcss to .ts aswell, Not sure whether you would prefer both to just be .js?

**Comment by algreasley** [comment]
> Managed to convert the tailwind config to .ts and the postcss to .js. Can't seem to get postcss to .ts aswell, Not sure whether you would prefer both to just be .js?
.. should have started a review/conversation/thread 😄 
I think this is fine for now .. if you can remove the package-lock.json, we can get this in 👍🏻

**Comment by adamshcao** [comment]
> > Managed to convert the tailwind config to .ts and the postcss to .js. Can't seem to get postcss to .ts aswell, Not sure whether you would prefer both to just be .js?
> > .. should have started a review/conversation/thread 😄
> > I think this is fine for now .. if you can remove the package-lock.json, we can get this in 👍🏻

Done :)

**Review by algreasley — APPROVED** [review]

**Pull request merged**
